<?php

/**
 * BasesfEasyCommentsPlaceholder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $identifier_key
 * @property Doctrine_Collection $Items
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id$
 */
abstract class BasesfEasyCommentsPlaceholder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_easy_comments_placeholder');
        $this->hasColumn('identifier_key', 'string', 32, array('type' => 'string', 'length' => '32'));
    }

    public function setUp()
    {
        $this->hasMany('sfEasyCommentsItem as Items', array('local' => 'id',
                                                            'foreign' => 'placeholder_id'));
    }
}