sfEasyCommentsPlaceholder:
  tableName: sf_easy_comments_placeholder
  columns:
    identifier_key: string(32)

sfEasyCommentsItem:
  tableName: sf_easy_comments_item
  actAs: [ Timestampable ]
  columns:
    placeholder_id: integer
    parent_id: integer
    body: string(4096)
    spam_value: integer
    author_name: string(64)
    author_email: string(128)
    author_website: string(128)
    author_notify_flag: boolean
    validation_flag: boolean
  relations:
    Placeholder:
      class: sfEasyCommentsPlaceholder
      foreignAlias: Items
      local:        placeholder_id
      foreign:      id
      type:         one
      foreignType:  many




